esphome:
  name: minecraft-ore1
  friendly_name: minecraft-ore1
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "++yIsgIsGjs/gdIR/7L+FRvxkBiXZMMIbITQwOM0Qds="

ota:
  - platform: esphome
    password: "fedf205ec380d1344b829f65287f70ab"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ore Setup Hotspot"
    password: "password"

captive_portal:


# Custom components
external_components:
  - source: 
      url: https://github.com/plomdawg/esphome-minecraft.git
      type: git
      ref: dev
    refresh: 0s
    components: [minecraft_server_checker]


# Server checker component
minecraft_server_checker:
  id: server_checker
  update_interval: 15s
  server_address: !lambda return id(server_address).state
  server_port: !lambda return id(server_port).state
  player_count:
    name: "Player Count"
  server_status:
    name: "Server Status"


text_sensor:
  - platform: template
    name: "Server Address"
    id: server_address
  - platform: template
    name: "Server Status"
    id: server_status

# LED Output
light:
  - platform: neopixelbus
    variant: WS2811
    type: GRB
    pin: D4
    num_leds: 1
    name: "Minecraft Ore Block LED"
    id: ore_block_led

# Button for manual control
binary_sensor:
  - platform: gpio
    pin: D3
    name: "Control Button"
    on_press:
      then:
        - light.toggle: ore_block_led
