esphome:
  name: minecraft-ore1
  friendly_name: minecraft-ore1
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "++yIsgIsGjs/gdIR/7L+FRvxkBiXZMMIbITQwOM0Qds="

ota:
  - platform: esphome
    password: "fedf205ec380d1344b829f65287f70ab"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ore Setup Hotspot"
    password: "password"

captive_portal:


# Custom components
external_components:
  - source: 
      url: https://github.com/plomdawg/esphome-minecraft.git
      type: git
      ref: dev
    refresh: 0s
    components: [minecraft_ore_block_config, minecraft_server_checker]

# Configuration component
minecraft_ore_block_config:
  id: ore_block_config

# Server checker component
minecraft_server_checker:
  id: server_checker
  config_id: ore_block_config
  player_count_id: player_count
  server_status_id: server_status
  update_interval: 15s

# LED control component
#minecraft_led_control:
#  id: led_control
#  config_id: ore_block_config
#  light_id: ore_block_led
#  player_count_sensor_id: player_count

# Sensors
sensor:
  - platform: template
    name: "Server Port"
    id: server_port
    icon: mdi:minecraft
  - platform: minecraft_server_checker
    name: "Player Count"
    id: player_count

text_sensor:
  - platform: template
    name: "Mode"
    id: mode
  - platform: template
    name: "Server Address"
    id: server_address
  - platform: template
    name: "Static Color"
    id: static_color
  - platform: minecraft_server_checker
    name: "Server Status"
    id: server_status

# LED Output
light:
  - platform: neopixelbus
    variant: WS2811
    type: GRB
    pin: D4
    num_leds: 1
    name: "Minecraft Ore Block LED"
    id: ore_block_led

# Button for manual control
binary_sensor:
  - platform: gpio
    pin: D3
    name: "Control Button"
    on_press:
      then:
        - light.toggle: ore_block_led
